# Generated by Django 4.0.4 on 2022-05-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(unique=True)),
                ('value', models.FloatField()),
                ('delivery_time', models.DateField()),
                ('value_at_rub', models.FloatField()),
            ],
        ),
    ]
